"""initial tables

Revision ID: 52bdaf4de4bd
Revises: 
Create Date: 2026-06-12 13:13:24.894607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52bdaf4de4bd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_table', sa.Column('slug', sa.String(), nullable=True))
    op.add_column('blog_table', sa.Column('meta_description', sa.String(length=160), nullable=True))
    op.add_column('blog_table', sa.Column('keywords', sa.JSON(), nullable=True))
    op.alter_column('blog_table', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('blog_table', 'introduction',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=True)
    op.alter_column('blog_table', 'content',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=True)
    op.alter_column('blog_table', 'conclusion',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_unique_constraint(None, 'blog_table', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blog_table', type_='unique')
    op.alter_column('blog_table', 'conclusion',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('blog_table', 'content',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=False)
    op.alter_column('blog_table', 'introduction',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=False)
    op.alter_column('blog_table', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('blog_table', 'keywords')
    op.drop_column('blog_table', 'meta_description')
    op.drop_column('blog_table', 'slug')
    # ### end Alembic commands ###
